name: Contributors_Lister
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          affiliation: all
          commitMessage: ":busts_in_silhouette: Updated Contributors List"
          includeBots: true
          round: true
          svgPath: CONTRIBUTORS.svg
          svgWidth: 100%
          userNameHeight: 40
