name: Delete_Workflow_History
on:
  schedule:
    - cron: 0 0 * * 3
  workflow_dispatch:
jobs:
  eradicate:
    runs-on: ubuntu-latest
    steps:
    - uses: otto-contentfactory/purge-workflow-runs@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: Mattraks/delete-workflow-runs@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 0
        keep_minimum_runs: 2
